[colors.primary]
background = "#303030"
foreground = "#c5c8c6"

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 4096

[window]
title = "Terminal"

[window.padding]
x = 8
y = 8
